#!/bin/bash

EXP_TYPE=$1
MANIFEST=$2
SCENARIO=$3
TIME=$4

python $PWD/selenium/selenium_steps.py $EXP_TYPE $MANIFEST $SCENARIO/Config.csv $TIME
sleep $TIME
cp ~/Downloads/*group*\(1* $SCENARIO/output.csv
rm ~/Downloads/*group*
