#!/bin/bash

EXP_TYPE=$1
MANIFEST=$2
SCENARIO=$3
TIME=$4

python $PWD/selenium/selenium_steps.py $EXP_TYPE $MANIFEST $SCENARIO/Config.csv $TIME

cp ~/Downloads/*group* $SCENARIO/output.csv
rm ~/Downloads/*group*
