#!/bin/bash

python /home/ubuntu/redwood-test-harness/selenium/selenium_steps.py HFT-CDA /home/daniel/Documents/Programming/LEEPS/Code/2.2/redwood/static/redwood-high-frequency-trading-remote/manifest.json /home/daniel/Documents/Programming/LEEPS/Code/2.2/redwood/static/experiments/redwood-high-frequency-trading-remote/config/test_config.csv 10

mv ~/Downloads/* ~/redwood-test-harness/data/scenarios/Scenario1/output.csv
